#!/bin/sh
exec 2>&1

PERL=/home/babyry/perl5/perlbrew/perls/perl-5.16.3/bin/perl
DAEMON=/home/babyry/BabyryApi5002/script/babyryapi-server

exec \
  envdir ./env \
  setuidgid babyry \
  $PERL $DAEMON
